### ISSUE TITLE
are you going to work on it in future

### ISSUE THREAD

**Issue by nitin2953** [Twometer/NoFences#1]
FIRST I get so excited that someone has listen to us,
then i download it and found it buggy,
my all expectations got killed at first sight

cheers to you for making this effort.

[i was not able to pull request thats why i posted here]

**Comment by Twometer** [comment]
Hi nitin, 
Nice that you like the project, appreciate that 😀 

Let me say that I did not expect this project to catch a lot of interest for someone else, and therefore only wrote it for me and only tested it there so I am not very surprised that it's buggy ;-) But I think I can fix some; what bugs exactly did you encounter?

**Comment by Twometer** [comment]
Are you still interested in bug fixes?

**Comment by Twometer** [comment]
I will close this for inactivity now, feel free to open a new issue if you got any other requests.
