### ISSUE TITLE
why do some antivirus classify nofences.exe as trojan?

### ISSUE THREAD

**Issue by LeonardoBTT** [Twometer/NoFences#10]
my browser blocked the download. It's safe?
https://www.hybrid-analysis.com/sample/b9e75d76b312d57f8aff7290529debaa3374dd777d6252852e29b76862059bb8

**Comment by Twometer** [comment]
Most antivirus programs falsely detect unsinged / self-written programs as viruses.
NoFences is completely safe. The source code is fully available, and the .exe from the download is just a convenience. If you don't trust the executable, you can download the source, check that it's virus-free, and build it yourself. :)
