### ISSUE TITLE
[REQUEST] Image Thumbnail Rendering

### ISSUE THREAD

**Issue by emerysteele** [Twometer/NoFences#11]
Would be cool if image thumbnails could be rendered like they do on the normal desktop, instead of just the default placeholder icon.

Also, awesome work so far!
Was looking for an alternative to Fences, their UI is so slow when moving a fence around, even if it is empty (believe it has to do with the way their fences interact with & move desktop icons around). But this is buttery smooth.

**Comment by emerysteele** [comment]
![NVIDIA_Share_B6nnZDptNj](https://user-images.githubusercontent.com/1169001/128624213-6f9b6aeb-d740-48df-8a57-1ff88b3a43d4.png)

**Comment by Twometer** [comment]
That sounds like a good idea, I'll see what I can do.
Glad that you like the project :) - Yes I believe the original Fences drag the Windows Icons around, NoFences is just a regular window on top of the desktop

**Comment by Twometer** [comment]
Added in release v1.7
