### ISSUE TITLE
Moving files - missing reference

### ISSUE THREAD

**Issue by Brada85** [Twometer/NoFences#3]
After adding an item into a fence and later moving the real file to a different location (changing its path), the fence stops working.

**Comment by Twometer** [comment]
Yes, the fences only save a reference. Does the icon only disappear or does the fence crash?

**Comment by Brada85** [comment]
The fencd crashes and all items in it are lost to.

**Comment by Twometer** [comment]
Okay, that should definitely not be like that, I will look at this

**Comment by Brada85** [comment]
Awesome, thanks.

**Comment by Twometer** [comment]
It should be fixed now. Files that don't exist are not shown and will no longer cause a crash.
v1.3 should have this fixed

**Comment by Brada85** [comment]
Thanks!!!
I did install it again and tried using it.
I am not able to add any items to any fence by drag&drop.

**Comment by Twometer** [comment]
You're welcome! For the other issue, try right-clicking on the fence and make sure that the `Lock` option is not checked.

**Comment by Brada85** [comment]
Cool, it works now. Don't know why, I reinstalled it and that seems to have fixed it.
The "Lock" option was not enabled earlier, so that should not have caused it.
Anyway, thanks alot, much appreciated!
