### ISSUE TITLE
Block sizes

### ISSUE THREAD

**Issue by Logoniuss** [Twometer/NoFences#4]
Hello, please do so that you can change the size of the blocks, they are too large

**Comment by Twometer** [comment]
Do you mean the size of the icons?

**Comment by Logoniuss** [comment]
> Вы имеете ввиду размер иконок?

No, the frame itself, where the header of the fence is, is too large, I want a small strip, the picture is attached what I mean.
https://i.imgur.com/E7PlH6p.png

**Comment by Twometer** [comment]
Ah, you mean the fence's header. I'll see if I can add an option for the header height into the options menu.

**Comment by Twometer** [comment]
I've released version 1.4 which now contains an option to change the height of the header blocks :^)

**Comment by Logoniuss** [comment]
Thank you very much, you are the best.
