### ISSUE TITLE
Right click the App, it doesn't show the properties of the software

### ISSUE THREAD

**Issue by LilaGraceAgripa** [Twometer/NoFences#5]
Hi, Thanks for the Great Software! 

When Right-click the App, it doesn't show the properties of the app, please advise if it possible to add this function?

Thanks and best regards

**Comment by Twometer** [comment]
I think it's possible to show the default right-click menu when right-clicking an app in a fence, I'll see what I can do :)

**Comment by LilaGraceAgripa** [comment]
Thanks so much!!!

**Comment by Twometer** [comment]
I've released version 1.5 which now contains a new feature that shows the Explorer right-click menu when clicking on an item
