### ISSUE TITLE
Scroll Bar

### ISSUE THREAD

**Issue by benwade233** [Twometer/NoFences#7]
Hi, It seems there isn't a scroll when there are many icons inside. Have you considered releasing a new version with Scroll Bar?

**Comment by Twometer** [comment]
Hm, that's actually a nice idea. I'll see what I can do

**Comment by benwade233** [comment]
Thanks! Look forward to it!
There is another issue that dragging the icons from the desktop to NoFences. The icons are still on the desktop, but if delete them from the Desktop, the same icons on the NoFences disappear.

**Comment by Twometer** [comment]
Yes, the items in nofences are just references to actual files on the disk, just like creating a shortcut in Windows. They do not copy the file.
Therefore, when you delete the original file, it will also remove the reference within the fence.

**Comment by benwade233** [comment]
Thanks for replying!
Is that possible to drag the folder to NoFences instead of its shortcut?

**Comment by Twometer** [comment]
It would be possible to move the item to another folder that is inside a private NoFence folder, but that would require some redesigning. Also, with that, you would have to wait for the moving process to complete, which could take quite a while with larger files

**Comment by Rick-Buring** [comment]
I Just came across this amazing tool and I missed the scroll function. so I thought I'll give it a try. So I made it and it is working. it isn't the prettiest solution but it is functional. So here is my solution maybe you can use it in a next release.

create onMouseScrollevent (in the FenceWindow class)

        private void OnMouseScroll(object sender, MouseEventArgs e)
        {
            offset += e.Delta/10;
            Refresh();
        }

in the InitializeComponent on the window add the listener (In the FenceWindowDesigner class):

            this.MouseWheel += new System.Windows.Forms.MouseEventHandler(this.OnMouseScroll);

create a offset attribute (in the FenceWindow class):

        private int offset = 0;

add the following to the RenderFile function (in the FenceWindow class):

            y += offset;
            if (y < 0 + Icon.Height)
                return;

**Comment by Twometer** [comment]
@Rick-Buring That's very nice, thank you. Scrolling will be implemented with the next release!

**Comment by Twometer** [comment]
Version 1.6 now has a scrollbar :)
